version: '3'

services:

  application:
    image: ldynia/conteneraized-workshop:2.0
    build: .
    restart: always
    container_name: demo
    volumes:
      - ./app/data-x/:/data-x
    environment:
      MAGIC: abbracadabbra
    command: sh scripts/startup.sh
